#!/bin/sh -e

export GTK_THEME=Adwaita
appdir=$(readlink -f ${APPDIR:-$(dirname "$0")})

desktopfile=$(ls -1 "$appdir"/*.desktop | head -n1)

if [ ! -f "$desktopfile" ]; then
    echo "No desktop file found!"
    exit 1
fi

exec "$appdir/usr/bin/emuferal-installer" "$@"
