/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_asf_windowsill_WMNI */

#ifndef _Included_org_asf_windowsill_WMNI
#define _Included_org_asf_windowsill_WMNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_asf_windowsill_WMNI
 * Method:    initRuntime
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_asf_windowsill_WMNI_initRuntime
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jstring);

/*
 * Class:     org_asf_windowsill_WMNI
 * Method:    loadMonoLib
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_asf_windowsill_WMNI_loadMonoLib
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_asf_windowsill_WMNI
 * Method:    loadLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_asf_windowsill_WMNI_loadLibrary
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_asf_windowsill_WMNI
 * Method:    librarySymbol
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_asf_windowsill_WMNI_librarySymbol
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_asf_windowsill_WMNI
 * Method:    closeLibrary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_asf_windowsill_WMNI_closeLibrary
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_asf_windowsill_WMNI
 * Method:    dlLoadError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_asf_windowsill_WMNI_dlLoadError
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
